### ISSUE TITLE
Inocrrect character in warning message

### ISSUE THREAD

**Issue by asashour** [neo4j-apps/neo4j-desktop#80]
Neo4jDesktop `1.2.7`
Neo4j `4.0.3`

There are incorrect characters in a warning message.

![image](https://user-images.githubusercontent.com/2410127/80680338-da5a6d00-8abe-11ea-9770-467d5098f594.png)

Steps to reproduce:
1. Create a new database
2. `create (:One)-[:SYNONYM]->(:One)`
3. `match (:One)-[b:SYNONYM*]-(:One) return b`

**Comment by akollegger** [comment]
Hi @asashour ,

I believe this has been fixed. The characters you note are whitespace. Could you confirm that the warning now appears correctly?

Thanks,
Andreas

**Comment by asashour** [comment]
Hi @akollegger 

I am afraid it is not fixed.

Neo4j Desktop: 1.2.8

Neo4j Browser version: 4.0.9

Neo4j Server version: 4.0.3 (enterprise)

![image](https://user-images.githubusercontent.com/2410127/83637183-789e8e80-a5a7-11ea-9f59-86b3c6d0983d.png)
